# Generated by Django 5.0.2 on 2024-07-07 05:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_favorited'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='licence',
            field=models.FileField(default='', upload_to='uploads/properties/licence'),
        ),
        migrations.CreateModel(
            name='PropertyVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_verified_by_staff', models.BooleanField(default=False)),
                ('is_verified_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_verification', to='property.property')),
                ('verified_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
