# Generated by Django 5.0.2 on 2024-07-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_reviews_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-created_at']},
        ),
    ]
