# Generated by Django 5.0.2 on 2024-07-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_reviews_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='adrress',
            field=models.TextField(default=''),
        ),
    ]
