# Generated by Django 5.0.2 on 2024-07-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_rename_adrress_property_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
    ]
